from tkinter import *
from tkinter import messagebox
root=Tk()
root.title("STUDENT REGISTRATION FORM")
root.geometry("600x800")
root.iconbitmap("MINIPROJECT/form.ico")
root.config(bg="lightblue")
label=Label(root,text="=============================",font=("Calibri",30),bg="lightblue",fg="green")
label.grid(row=0,column=0,columnspan=2,pady=3)
label=Label(root,text="STUDENT REGISTRATION FORM",font=("Calibri",30),bg="lightblue",fg="green")
label.grid(row=1,column=0,columnspan=2,pady=3) 
label=Label(root,text="=============================",font=("Calibri",30),bg="lightblue",fg="green")
label.grid(row=2,column=0,columnspan=2,pady=3)

name_label=Label(root,text="Name:",font=("Arial",14),bg="lightblue")
name_label.grid(row=4,column=0,padx=10,pady=10,sticky='w')
name_entry=Entry(root,font=("Arial",14))
name_entry.grid(row=4,column=1,padx=10,pady=10)
father_name_label=Label(root,text="Father's Name:",font=("Arial",14),bg="lightblue")
father_name_label.grid(row=5,column=0,padx=10,pady=10,sticky='w')
father_name_entry=Entry(root,font=("Arial",14))
father_name_entry.grid(row=5,column=1,padx=10,pady=10)
mother_name_label=Label(root,text="Mother's Name:",font=("Arial",14),bg="lightblue")
mother_name_label.grid(row=6,column=0,padx=10,pady=10,sticky='w')
mother_name_entry=Entry(root,font=("Arial",14)) 
mother_name_entry.grid(row=6,column=1,padx=10,pady=10)
phone_label=Label(root,text="Phone number:-",font=("Arial",14),bg="lightblue")
phone_label.grid(row=9,column=0,padx=10,pady=10,sticky='w')
phone_entry=Entry(root,font=("Arial",14))
phone_entry.grid(row=9,column=1,padx=10,pady=10)
email_label=Label(root,text="Email:-",font=("Arial",14),bg="lightblue")
email_label.grid(row=7,column=0,padx=10,pady=10,sticky='w') 
email_entry=Entry(root,font=("Arial",14))
email_entry.grid(row=7,column=1,padx=10,pady=10)
gender_choice=StringVar()
gender_label=Label(root,text="Gender:-",font=("Arial",14),bg="lightblue")
gender_label.grid(row=8,column=0,padx=10,pady=10,sticky='w')
gender_male=Radiobutton(root,text="Male",variable=gender_choice,value="Male",font=("Arial",14),bg="lightblue")
gender_male.grid(row=8,column=1,padx=10,pady=10,sticky='w')
gender_female=Radiobutton(root,text="Female",variable=gender_choice,value="Female",font=("Arial",14),bg="lightblue")
gender_female.grid(row=8,column=1,padx=10,pady=10,sticky='e')
date_of_birth_label=Label(root,text="Date of Birth:-",font=("Arial",14),bg="lightblue")
date_of_birth_label.grid(row=10,column=0,padx=10,pady=10,sticky='w')
date_of_birth_entry=Entry(root,font=("Arial",14))   
date_of_birth_entry.grid(row=10,column=1,padx=10,pady=10)
address_label=Label(root,text="Address:-",font=("Arial",14),bg="lightblue")
address_label.grid(row=11,column=0,padx=10,pady=10,sticky='w')
address_entry=Entry(root,font=("Arial",14))
address_entry.grid(row=11,column=1,padx=10,pady=10)
blood_group_check=StringVar()
blood_group_label=Label(root,text="Blood Group:-",font=("Arial",14),bg="lightblue")
blood_group_label.grid(row=12,column=0,padx=10,pady=10,sticky='w')
blood_group_a=Radiobutton(root,text="A",variable=blood_group_check,value="A",font=("Arial",14),bg="lightblue")
blood_group_a.grid(row=12,column=1,padx=10,pady=10,sticky='w')
blood_group_b=Radiobutton(root,text="B",variable=blood_group_check,value="B",font=("Arial",14),bg="lightblue")
blood_group_b.grid(row=12,column=1,padx=10,pady=10)
blood_group_ab=Radiobutton(root,text="AB",variable=blood_group_check,value="AB",font=("Arial",14),bg="lightblue")
blood_group_ab.grid(row=12,column=1,padx=10,pady=10,sticky='e')
department_label=Label(root,text="Department:-",font=("Arial",14),bg="lightblue")
department_label.grid(row=13,column=0,padx=10,pady=10,sticky='w')
department_entry=Entry(root,font=("Arial",14))
department_entry.grid(row=13,column=1,padx=10,pady=10)
course_label=Label(root,text="Course:-",font=("Arial",14),bg="lightblue")
course_label.grid(row=14,column=0,padx=10,pady=10,sticky='w')
course_entry=Entry(root,font=("Arial",14))  
course_entry.grid(row=14,column=1,padx=10,pady=10)
photo_entry_button=Button(root,text="Upload Photo",font=("Arial",14),bg="lightblue",command=lambda:messagebox.showinfo("Info","Photo uploaded successfully!"))
photo_entry_button.grid(row=15,column=0,columnspan=2,pady=20)
def submit_form():
    name=name_entry.get()
    father_name_entry.get()
    print("Name:",name)
    print("Father's Name:",father_name_entry.get())
    print("Mother's Name:",mother_name_entry.get())
    print("Phone number:",phone_entry.get())
    print("Email:",email_entry.get())
    print("Gender:",gender_choice.get())
    print("Date of Birth:",date_of_birth_entry.get())   
    print("Address:",address_entry.get())
    print("Blood Group:",blood_group_check.get())
    print("Department:",department_entry.get())
    print("Course:",course_entry.get())
    name=name_entry.get()
    if name.isalpha()==False:
        messagebox.showerror("Error","Name must contain only letters!")
        return False
    elif not name or not father_name_entry.get() or not mother_name_entry.get() or not phone_entry.get() or not email_entry.get() or not gender_choice.get() or not date_of_birth_entry.get() or not address_entry.get() or not blood_group_check.get() or not department_entry.get() or not course_entry.get():
        messagebox.showerror("Error","All fields are required!")
        return False
    elif not phone_entry.get().isdigit():
        messagebox.showerror("Error","Phone number must be a number!")
        return False
    elif  not len(phone_entry.get())==10:
        messagebox.showerror("Error","Phone number must be 10 digits!")
        return False
    elif not email_entry.get().count("@") or not email_entry.get().count("."):
        messagebox.showerror("Error","Invalid email address!")
        return False
    else:
        label=Label(root,text="Form submitted successfully!",font=("Arial",14),bg="lightblue",fg="green")
        label.grid(row=16,column=0,columnspan=2,pady=10)
    return True
def clear_form():
    name_entry.delete(0,END)
    father_name_entry.delete(0,END)
    mother_name_entry.delete(0,END)
    phone_entry.delete(0,END)
    email_entry.delete(0,END)
    gender_choice.set("")
    date_of_birth_entry.delete(0,END)
    address_entry.delete(0,END)
    blood_group_check.set("")
    department_entry.delete(0,END)
    course_entry.delete(0,END)
submit_button=Button(root,text="Submit",font=("Arial",14),bg="blue",fg="white",command=submit_form)
submit_button.grid(row=15,column=0,padx=10,pady=20)
clear_button=Button(root,text="Clear",font=("Arial",14),bg="red",fg="white",command=clear_form)
clear_button.grid(row=15,column=1,padx=10,pady=20)
root.mainloop()
